version: '3.8'

services:
  spark_engine:
    build: .
    container_name: telecom_spark_engine

    volumes:
      # Mount your project folder into container
      - .:/workspace

    working_dir: /workspace

    tty: true
    stdin_open: true

    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - PYSPARK_PYTHON=python3

    command: tail -f /dev/null